version: '3'
services:

  dsw-server:
    image: datastewardshipwizard/wizard-server:3.28
    restart: always
    ports:
    # (!!) Expose only for local deployment, externally use HTTPS proxy
      - 127.0.0.1:3001:3000
    depends_on:
      - postgres
      - minio
    volumes:
      - ./application.yml:/app/config/application.yml:ro
    extra_hosts:
      - host.docker.internal:host-gateway
    platform: linux/amd64

  dsw-client:
    image: datastewardshipwizard/wizard-client:3.28
    restart: always
    ports:
    # (!!) Expose only for local deployment, externally use HTTPS proxy
      - 127.0.0.1:8081:8080
    environment:
      API_URL: http://localhost:3001
    platform: linux/amd64

  docworker:
    image: datastewardshipwizard/document-worker:3.28
    restart: always
    depends_on:
      - postgres
      - minio
      - dsw-server
    volumes:
      - ./application.yml:/app/config/application.yml:ro
    extra_hosts:
      - host.docker.internal:host-gateway
    platform: linux/amd64

  mailer:
    image: datastewardshipwizard/mailer:3.28
    restart: always
    depends_on:
      - postgres
      - dsw-server
    volumes:
      - ./application.yml:/app/config/application.yml:ro
    platform: linux/amd64

  postgres:
    image: postgres:15.2
    restart: always
    # (!!) Expose only for debugging locally
    # ports:
    #   - 127.0.0.1:5432:5432
    # (!!) Change default password
    environment:
      POSTGRES_DB: engine-wizard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # (!!) Mount for persistent data
    # volumes:
    #  - db-data:/var/lib/postgresql/data
    # OR
    #  - ./db-data/data:/var/lib/postgresql/data
    platform: linux/amd64

  minio:
    image: minio/minio:RELEASE.2022-02-24T22-12-01Z
    restart: always
    command: server /data --console-address ":9001"
    # (!!) Expose only for debugging locally, externally use HTTPS proxy (see MinIO docs)
    ports:
      - 9000:9000
      - 9001:9001
    # (!!) Change default password
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minioPassword
    # (!!) Mount and backup for persistent data
    # volumes:
    #  - s3-data:/data
    # OR
    #  - ./s3-data/data:/data
    platform: linux/amd64

# volumes:
#   db-data:
#   s3-data: